### ISSUE TITLE
Is there a replacement for this repository?

### ISSUE THREAD

**Issue by alejoasotelo** [joomla-framework/cache#30]
Hi Guys! I really appreciate your work, Is awesome!

I saw this repository is deprecated and i would like to know if exists a replacement or what Joomla CMS will be using in the future.

Should i use another cache repo like symfony/cache or something like that?

Best!

**Comment by mbabker** [comment]
The CMS itself will continue using the classes in the `Joomla\CMS\Cache` namespace (not standalone from that repo), part of the reasoning is the CMS' cache needs don't directly align with either caching PSR and it didn't make too much sense to maintain two caching APIs, especially when PSR compatible packages are a dime a dozen.

As a replacement for this repo, if you were using the 2.0-dev branch then anything PSR-6 or PSR-16 would be fine (I switched some `joomla.org` apps from `joomla/cache` to `symfony/cache` with minimal effort thanks to the PSRs, biggest effort was in the DI container config).  The master branch (1.x stable releases) is a little more work since those shipped based on a very dated version of PSR-6 that's for the most part not compatible with what finally was voted in.

**Comment by alejoasotelo** [comment]
Ok i understand. I will switch to another cache system. 

Thank you very much for the quick answer!
